/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../Cap.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} scale={[1.98, 1.98, 1.98]} />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 0.09, 2.21]}
        scale={[2.01, -0.06, 1.88]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.02, 1.73, 0.01]}
        scale={[0.3, 0.3, 0.3]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        rotation={[0, -0.27, 0]}
        scale={[1.98, 1.98, 1.98]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        rotation={[0, -0.07, 0]}
        scale={[1.98, 1.98, 1.98]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[0.12, -0.01, -0.04]}
        scale={[1.98, 1.98, 1.98]}
      />
    </group>
  )
}

useGLTF.preload('/Cap.glb')
