/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../CubeEBody.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['default']}
        geometry={nodes['Render_Generic_QB_(v21~recovered)'].geometry}
        scale={[0.01, 0.01, 0.01]}>
        <meshStandardMaterial color='black'/>
        </mesh>
    </group>
  )
}

useGLTF.preload('../../../CubeEBody.gltf')
